Public Class Gates_Redistribution_module_TableLayout_Gates

    Public Shared Function Load()

        If Form_Tools.CheckBox_Gates_mode.Checked = True And Form_Tools.TableLayoutPanel_Npc.Visible = False Then
        ElseIf Form_Tools.CheckBox_Gates_mode.Checked = True Then
            Form_Tools.TableLayoutPanel_Npc.Visible = False
            Form_Tools.TableLayoutPanel_Gates.Visible = True

            Form_Tools.CheckedListBox_Gates.Items.Add("Alpha")
            Form_Tools.CheckedListBox_Gates.Items.Add("Beta")
            Form_Tools.CheckedListBox_Gates.Items.Add("Gamma")
            Form_Tools.CheckedListBox_Gates.Items.Add("Delta")
            Form_Tools.CheckedListBox_Gates.Items.Add("Epsilon")
            Form_Tools.CheckedListBox_Gates.Items.Add("Zeta")
            Form_Tools.CheckedListBox_Gates.Items.Add("Kappa")
            Form_Tools.CheckedListBox_Gates.Items.Add("Lambda")
            Form_Tools.CheckedListBox_Gates.Items.Add("Hades")
            Form_Tools.CheckedListBox_Gates.Items.Add("Chronos")
            Form_Tools.CheckedListBox_Gates.Items.Add("Kuiper")
            Form_Tools.CheckedListBox_Gates.Items.Add("Low")
            Form_Tools.CheckedListBox_Gates.Items.Add("QZ")

        Else
            Form_Tools.CheckedListBox_Gates.Items.Clear()
            Form_Tools.TableLayoutPanel_Gates.Visible = False
            Form_Tools.TableLayoutPanel_Npc.Visible = True
            Exit Function
        End If

        If Form_Tools.CheckedListBox_Gates.GetItemChecked(1) Then

            Form_Tools.CheckedListBox_Gates_npc.Items.Clear()
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Streuner")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Lordakia")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Mordon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Saimon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Devolarium")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Kristallin")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Sibelon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Sibelonit")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Kristallon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Protegit")

            Form_Tools.CheckedListBox_stop_at.Items.Clear()
            Form_Tools.CheckedListBox_stop_at.Items.Add("1")
            Form_Tools.CheckedListBox_stop_at.Items.Add("2")
            Form_Tools.CheckedListBox_stop_at.Items.Add("3")
            Form_Tools.CheckedListBox_stop_at.Items.Add("4")
            Form_Tools.CheckedListBox_stop_at.Items.Add("5")
            Form_Tools.CheckedListBox_stop_at.Items.Add("6")
            Form_Tools.CheckedListBox_stop_at.Items.Add("7")
            Form_Tools.CheckedListBox_stop_at.Items.Add("8")
            Form_Tools.CheckedListBox_stop_at.Items.Add("9")
            Form_Tools.CheckedListBox_stop_at.Items.Add("10")

            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Clear()
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("1")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("2")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("3")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("4")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("5")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("6")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("7")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("8")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("9")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("10")

            Form_Tools.CheckedListBox_Kamikaze.Items.Clear()
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("1")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("2")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("3")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("4")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("5")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("6")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("7")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("8")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("9")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("10")

            Form_Tools.CheckedListBox_Ammo1.Items.Clear()
            Form_Tools.CheckedListBox_Ammo1.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("10")

            Form_Tools.CheckedListBox_Ammo2.Items.Clear()
            Form_Tools.CheckedListBox_Ammo2.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("10")

            Form_Tools.CheckedListBox_Ammo3.Items.Clear()
            Form_Tools.CheckedListBox_Ammo3.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("10")

            Form_Tools.CheckedListBox_Ammo4.Items.Clear()
            Form_Tools.CheckedListBox_Ammo4.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("10")

        ElseIf Form_Tools.CheckedListBox_Gates.GetItemChecked(6) Then

            Form_Tools.CheckedListBox_Gates_npc.Items.Clear()
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Infernal")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Scorcher")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Melter")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Devourer")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Streuner")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Boss_Streuner")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Uber_Streuner")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Lordakia")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Boss_Lordakia")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Uber_Lordkia")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Saimon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Boss_Saimon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Uber_Saimon")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Sibelonit")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Boss_Sibelonit")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Uber_Sibelonit")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Kristallin")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Boss_Kristallin")
            Form_Tools.CheckedListBox_Gates_npc.Items.Add("Uber_Kristallin")

            Form_Tools.CheckedListBox_Ammo1.Items.Clear()
            Form_Tools.CheckedListBox_Ammo1.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("10")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("11")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("12")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("13")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("14")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("15")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("16")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("17")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("18")
            Form_Tools.CheckedListBox_Ammo1.Items.Add("19")

            Form_Tools.CheckedListBox_Ammo2.Items.Clear()
            Form_Tools.CheckedListBox_Ammo2.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("10")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("11")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("12")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("13")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("14")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("15")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("16")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("17")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("18")
            Form_Tools.CheckedListBox_Ammo2.Items.Add("19")

            Form_Tools.CheckedListBox_Ammo3.Items.Clear()
            Form_Tools.CheckedListBox_Ammo3.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("10")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("11")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("12")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("13")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("14")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("15")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("16")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("17")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("18")
            Form_Tools.CheckedListBox_Ammo3.Items.Add("19")

            Form_Tools.CheckedListBox_Ammo4.Items.Clear()
            Form_Tools.CheckedListBox_Ammo4.Items.Add("1")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("2")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("3")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("4")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("5")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("6")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("7")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("8")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("9")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("10")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("11")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("12")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("13")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("14")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("15")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("16")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("17")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("18")
            Form_Tools.CheckedListBox_Ammo4.Items.Add("19")

            Form_Tools.CheckedListBox_stop_at.Items.Clear()
            Form_Tools.CheckedListBox_stop_at.Items.Add("1")
            Form_Tools.CheckedListBox_stop_at.Items.Add("2")
            Form_Tools.CheckedListBox_stop_at.Items.Add("3")
            Form_Tools.CheckedListBox_stop_at.Items.Add("4")
            Form_Tools.CheckedListBox_stop_at.Items.Add("5")
            Form_Tools.CheckedListBox_stop_at.Items.Add("6")
            Form_Tools.CheckedListBox_stop_at.Items.Add("7")
            Form_Tools.CheckedListBox_stop_at.Items.Add("8")
            Form_Tools.CheckedListBox_stop_at.Items.Add("9")
            Form_Tools.CheckedListBox_stop_at.Items.Add("10")
            Form_Tools.CheckedListBox_stop_at.Items.Add("11")
            Form_Tools.CheckedListBox_stop_at.Items.Add("12")
            Form_Tools.CheckedListBox_stop_at.Items.Add("13")
            Form_Tools.CheckedListBox_stop_at.Items.Add("14")
            Form_Tools.CheckedListBox_stop_at.Items.Add("15")
            Form_Tools.CheckedListBox_stop_at.Items.Add("16")
            Form_Tools.CheckedListBox_stop_at.Items.Add("17")
            Form_Tools.CheckedListBox_stop_at.Items.Add("18")
            Form_Tools.CheckedListBox_stop_at.Items.Add("19")

            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Clear()
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("1")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("2")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("3")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("4")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("5")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("6")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("7")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("8")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("9")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("10")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("11")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("12")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("13")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("14")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("15")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("16")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("17")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("18")
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Add("19")

            Form_Tools.CheckedListBox_Kamikaze.Items.Clear()
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("1")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("2")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("3")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("4")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("5")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("6")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("7")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("8")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("9")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("10")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("11")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("12")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("13")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("14")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("15")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("16")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("17")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("18")
            Form_Tools.CheckedListBox_Kamikaze.Items.Add("19")

        Else Form_Tools.CheckedListBox_Gates_npc.Items.Clear()
            Form_Tools.CheckedListBox_Ammo1.Items.Clear()
            Form_Tools.CheckedListBox_Ammo2.Items.Clear()
            Form_Tools.CheckedListBox_Ammo3.Items.Clear()
            Form_Tools.CheckedListBox_Ammo4.Items.Clear()
            Form_Tools.CheckedListBox_Kamikaze.Items.Clear()
            Form_Tools.CheckedListBox_Kamikaz_corner.Items.Clear()
            Form_Tools.CheckedListBox_stop_at.Items.Clear()

        End If

    End Function

End Class
